title: Theodore Decker
logo: /assets/img/ted.png

description: 
The Pennsylvania State University, University Park, PA
Candidate for Graduation in May 2019
Bachelor of Science in Security and Risk Analysis
- Emphasis on Information & Cyber Security
show_downloads: false
theme: jekyll-theme-minimal
