title: Theodore Decker
logo: /assets/img/ted.png

description: Contact Information ted.decker12@gmail.com (Personal) decker.theodore12@gmail.com (Professional)
show_downloads: true
theme: jekyll-theme-minimal
